steps:
  # Step 1: Membuat image Docker dari aplikasi backend (berada di folder backend)
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ta-tcc-be", "."]
    dir: "backend"  # Menentukan folder backend untuk proses build

  # Step 2: Meng-upload/push image Docker ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ta-tcc-be"]
    dir: "backend"  # Menentukan folder backend untuk proses push

  # Step 3: Melakukan deploy ke Cloud Run menggunakan image yang telah di-push
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be-rest",
        "--image",
        "gcr.io/$PROJECT_ID/tcc-be-rest",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
    dir: "backend"  # Menentukan folder backend untuk menjalankan gcloud deploy

# Pengaturan logging untuk build hanya menggunakan Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
