steps:
 #step 0 menambahkan env
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "backend"  # Path ke folder backend untuk menyalin file .env
  # Step 1: Build Docker image for backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be-rest", "."]
    dir: "backend"  # Path ke folder backend untuk build Docker

  # Step 2: Push Docker image to Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be-rest"]
    dir: "backend"  # Path ke folder backend untuk push Docker image

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "be-rest",  # Nama layanan Cloud Run
        "--image", "gcr.io/$PROJECT_ID/tcc-be-rest",  # Nama image Docker
        "--timeout", "300s",  # Timeout 5 menit
        "--port", "8080",  # Port yang digunakan oleh Cloud Run
        "--region", "us-central1",  # Region tempat layanan Cloud Run
        "--allow-unauthenticated"  # Memberikan akses publik ke layanan
      ]
    dir: "backend"  # Path ke folder backend

  # Step 4: Set IAM policy to allow public access
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta", "run", "services", "add-iam-policy-binding", 
        "--region=us-central1", 
        "--member=allUsers", 
        "--role=roles/run.invoker", 
        "be-rest"  # Nama layanan Cloud Run
      ]
    dir: "backend"

options:
  logging: CLOUD_LOGGING_ONLY
